# Generated by Django 2.2.3 on 2020-09-08 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('version', models.CharField(max_length=64, verbose_name='版本信息')),
                ('type', models.CharField(choices=[('Web', 'Web'), ('App', 'App')], default='Web', max_length=16, verbose_name='项目类型')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('description', models.CharField(max_length=256, verbose_name='项目描述')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('createUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目信息',
            },
        ),
    ]
